/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uno.client;

/**
 *
 * @author Nicole
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jLabelStack = new javax.swing.JLabel();
        stackBtn = new javax.swing.JButton();
        card7Btn = new javax.swing.JButton();
        card6Btn = new javax.swing.JButton();
        card5Btn = new javax.swing.JButton();
        crard4Btn = new javax.swing.JButton();
        card3Btn = new javax.swing.JButton();
        card2Btn = new javax.swing.JButton();
        card1Btn = new javax.swing.JButton();
        moreCardsBtn = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        unoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerList = new javax.swing.JLabel();
        jLabelBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setBackground(new java.awt.Color(153, 102, 0));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(2360, 20, 180, 60));

        jLabelStack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(jLabelStack, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, -1, -1));

        stackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UNO.png"))); // NOI18N
        getContentPane().add(stackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 190, 310, -1));

        card7Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(card7Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(2190, 940, 250, 370));

        card6Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        card6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card6BtnActionPerformed(evt);
            }
        });
        getContentPane().add(card6Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 940, 250, 370));

        card5Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(card5Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 940, 250, 370));

        crard4Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(crard4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 940, 250, 370));

        card3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(card3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 940, 250, 370));

        card2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(card2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 940, 250, 370));

        card1Btn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        card1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blank.png"))); // NOI18N
        getContentPane().add(card1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 940, 250, 370));

        moreCardsBtn.setBackground(new java.awt.Color(204, 153, 0));
        moreCardsBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        moreCardsBtn.setForeground(new java.awt.Color(255, 255, 255));
        moreCardsBtn.setText("Next Cards ->");
        moreCardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreCardsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(moreCardsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(2170, 1380, 300, 100));

        messageLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 255));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Your turn!");
        messageLabel.setAlignmentX(0.5F);
        getContentPane().add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1400, 1680, 140));

        unoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnUNO.png"))); // NOI18N
        unoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(unoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1950, 420, 440, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Other players: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        playerList.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        playerList.setForeground(new java.awt.Color(255, 255, 255));
        playerList.setText("P2: 7 cards");
        playerList.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(playerList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 340, 660));

        jLabelBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mesa.jpg"))); // NOI18N
        getContentPane().add(jLabelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);   
    }//GEN-LAST:event_exitButtonActionPerformed

    private void card6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card6BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card6BtnActionPerformed

    private void moreCardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreCardsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreCardsBtnActionPerformed

    private void unoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton card1Btn;
    private javax.swing.JButton card2Btn;
    private javax.swing.JButton card3Btn;
    private javax.swing.JButton card5Btn;
    private javax.swing.JButton card6Btn;
    private javax.swing.JButton card7Btn;
    private javax.swing.JButton crard4Btn;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackGround;
    private javax.swing.JLabel jLabelStack;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton moreCardsBtn;
    private javax.swing.JLabel playerList;
    private javax.swing.JButton stackBtn;
    private javax.swing.JButton unoBtn;
    // End of variables declaration//GEN-END:variables
}
